hh<-read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?",)
(hh <- hh[with(hh, hh$Date == "1/2/2007" | hh$Date == "2/2/2007"), ])
time <- as.POSIXct(paste(hh$Date, hh$Time), format = "%d/%m/%Y %H:%M:%S")
png("plot3.png", width = 480, height = 480)
plot(range(time), range(hh$Sub_metering_1, hh$Sub_metering_2, hh$Sub_metering_3), xlab = "", ylab = "Energy submetering", type="n")
lines(time, hh$Sub_metering_1, col ="black")
lines(time, hh$Sub_metering_2, col ="red")
lines(time, hh$Sub_metering_3, col ="blue")
legend("topright", legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"),  lty=1, cex=.8, bty = "1")
dev.off()