hh<-read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?",)
(hh <- hh[with(hh, hh$Date == "1/2/2007" | hh$Date == "2/2/2007"), ])
time <- as.POSIXct(paste(hh$Date, hh$Time), format = "%d/%m/%Y %H:%M:%S")
png("plot4.png", width = 480, height = 480)
par (mfrow = c(2,2))
plot(range(time), range(hh$Global_active_power), xlab = "", ylab = "Global Active Power(kilowatts)", type="n", cex.axis = 0.8, cex.lab = 0.7)
lines(time, hh$Global_active_power)
plot(range(time), range(hh$Voltage), xlab = "datatime", ylab = "Voltage", type="n", cex.axis = 0.8, cex.lab = 0.7)
lines(time, hh$Voltage)
plot(range(time), range(hh$Sub_metering_1, hh$Sub_metering_2, hh$Sub_metering_3), xlab = "", ylab = "Energy submetering", type="n", cex.axis = 0.8, cex.lab = 0.7)
lines(time, hh$Sub_metering_1, col ="black")
lines(time, hh$Sub_metering_2, col ="red")
lines(time, hh$Sub_metering_3, col ="blue")
legend("topright", legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"),  lty=1, cex=.8, bty = "n")
plot(range(time), range(hh$Global_reactive_power), xlab = "datetime", ylab = "Global_reactive_power", type="n", cex.axis = 0.8, cex.lab = 0.7)
lines(time, hh$Global_reactive_power)
dev.off()


